### ISSUE TITLE
Pandora CLI is not copied in %LocalAppData%

### ISSUE THREAD

**Issue by sdluxeon** [Elders/Nyx#4]
Pandora CLI is not coppied in %LocalAppData% which makes the deployment of configurations in consul to fail.
**Steps to reproduce:**

- Delete %ProgramData%\Elders
- Delete %LocalAppData%\Pandora.Cli
- Run qore.configuration\qore.contacts\qore.contacts.configuration@consul.bat

**Comment by mynkow** [comment]
We are now using these folders
```
SET ROOT=%ALLUSERSPROFILE%\Elders
SET NUGET=%ROOT%\NuGet\NuGet.exe
SET FAKE=%ROOT%\FAKE\tools\Fake.exe
SET NYX=%ROOT%\Nyx\tools\build_next.fsx
SET GITVERSION=%ROOT%\GitVersion.CommandLine\tools\GitVersion.exe
```

https://github.com/Elders/Nyx/blob/master/.nyx/get-dependencies.cmd

**Comment by sdluxeon** [comment]
Arent we missing SET PANDORA_CLI 
https://github.com/Elders/Nyx/blob/master/.nyx/get-pandora.cli.cmd#L5

**Comment by mynkow** [comment]
Someone has to rewrite these local bat files. The Pandora.cli.cmd which you are referring to is used in deployment which is another workflow. You can quickly hack the current script or rewrite it in such way that we can reuse the dependencies parts.

**Comment by sdluxeon** [comment]
Cool 10x
